# Generated by Django 5.0.7 on 2024-07-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('description', models.TextField(max_length=150)),
                ('price_per_month', models.SmallIntegerField(default=0)),
                ('lessons_count', models.SmallIntegerField(default=0)),
                ('lessons_duration', models.TimeField()),
                ('pupils_count', models.SmallIntegerField(default=0)),
                ('team_lead', models.BooleanField(default=False)),
                ('team_lead_name', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=50)),
                ('support_phone_number', models.CharField(max_length=9)),
                ('start_date', models.DateField()),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vahe_project.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
