# Generated by Django 5.0.7 on 2024-07-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahe_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons_duration',
            field=models.CharField(max_length=10),
        ),
    ]
